<Project Sdk="Microsoft.NET.Sdk.Worker">

  <Sdk Name="StuDev.AotAnywhere" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <PublishAot>true</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HyPanel.Shared\HyPanel.Shared.csproj" />
  </ItemGroup>
</Project>
