namespace HyPanel.Server.Endpoints;
using HyPanel.Server.Updates;
using HyPanel.Server.Persistence;
using HyPanel.Server.Backup;
using HyPanel.Server.Backends;

using System.Text.Json.Serialization;
using HyPanel.Shared.Contracts;

[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
[JsonSerializable(typeof(CreateNodeRequest))]
[JsonSerializable(typeof(CreateNodeResponse))]
[JsonSerializable(typeof(CreateEnrollmentTokenResponse))]
[JsonSerializable(typeof(AdminNodeObservationResponse[]))]
[JsonSerializable(typeof(NodeMetrics))]
[JsonSerializable(typeof(CreateHealthCheckCommandResponse))]
[JsonSerializable(typeof(CreateDiagnosticCommandResponse))]
[JsonSerializable(typeof(ServiceDiagnosticResponse[]))]
[JsonSerializable(typeof(InstallCommandRequest))]
[JsonSerializable(typeof(InstallCommandResponse))]
[JsonSerializable(typeof(CreateServiceRequest))]
[JsonSerializable(typeof(UpdateServiceRequest))]
[JsonSerializable(typeof(SetServiceEnabledRequest))]
[JsonSerializable(typeof(SetBackendUpdatePolicyRequest))]
[JsonSerializable(typeof(RequestBackendUpdateResponse))]
[JsonSerializable(typeof(ServerUpdateRequestResponse))]
[JsonSerializable(typeof(ServerUpdateStatus))]
[JsonSerializable(typeof(UpdateGlobalSettingsRequest))]
[JsonSerializable(typeof(GlobalSettingsResponse))]
[JsonSerializable(typeof(GlobalSettingsRecord))]
[JsonSerializable(typeof(ServiceMutationResponse))]
[JsonSerializable(typeof(AdminServiceResponse[]))]
[JsonSerializable(typeof(LoginRequest))]
[JsonSerializable(typeof(LoginResponse))]
[JsonSerializable(typeof(UserResponse))]
[JsonSerializable(typeof(UserGroupRequest))]
[JsonSerializable(typeof(SubscriptionTemplateRequest))]
[JsonSerializable(typeof(SubscriptionTemplateResponse))]
[JsonSerializable(typeof(SubscriptionTemplateError))]
[JsonSerializable(typeof(CertificateErrorResponse))]
[JsonSerializable(typeof(UserGroupResponse))]
[JsonSerializable(typeof(UserGroupResponse[]))]
[JsonSerializable(typeof(UserResponse[]))]
[JsonSerializable(typeof(CreateUserRequest))]
[JsonSerializable(typeof(UpdateUserRequest))]
[JsonSerializable(typeof(CreateUserResponse))]
[JsonSerializable(typeof(RotateSubscriptionTokenResponse))]
[JsonSerializable(typeof(UserServiceAccessResponse[]))]
[JsonSerializable(typeof(UsageTotalResponse[]))]
[JsonSerializable(typeof(Guid[]))]
[JsonSerializable(typeof(ServicePublicEndpointRequest))]
[JsonSerializable(typeof(ServicePublicEndpointResponse))]
[JsonSerializable(typeof(BatchServiceEnabledRequest))]
[JsonSerializable(typeof(BatchServiceEnabledResponse))]
[JsonSerializable(typeof(HealthSummaryResponse))]
[JsonSerializable(typeof(SetAgentUpdatePolicyRequest))]
[JsonSerializable(typeof(RequestAgentUpdateResponse))]
[JsonSerializable(typeof(BatchAgentUpdateRequest))]
[JsonSerializable(typeof(BatchAgentUpdateResponse))]
[JsonSerializable(typeof(CertificateUploadRequest))]
[JsonSerializable(typeof(CertificateResponse))]
[JsonSerializable(typeof(CertificateResponse[]))]
[JsonSerializable(typeof(BackupSummary))]
[JsonSerializable(typeof(IReadOnlyList<BackupSummary>))]
[JsonSerializable(typeof(BackupValidation))]
[JsonSerializable(typeof(RestoreRequest))]
[JsonSerializable(typeof(RestoreResponse))]
[JsonSerializable(typeof(BackupErrorResponse))]
[JsonSerializable(typeof(BackendDefinitionResponse))]
[JsonSerializable(typeof(BackendDefinitionResponse[]))]
[JsonSerializable(typeof(BackendFieldDefinition))]
[JsonSerializable(typeof(BackendDefaultsResponse))]
internal sealed partial class ServerJsonSerializerContext : JsonSerializerContext;
