namespace HyPanel.Server.Endpoints;
using HyPanel.Server.Updates;

using System.Text.Json.Serialization;
using HyPanel.Shared.Contracts;

[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
[JsonSerializable(typeof(CreateNodeRequest))]
[JsonSerializable(typeof(CreateNodeResponse))]
[JsonSerializable(typeof(CreateEnrollmentTokenResponse))]
[JsonSerializable(typeof(AdminNodeObservationResponse[]))]
[JsonSerializable(typeof(NodeMetrics))]
[JsonSerializable(typeof(CreateHealthCheckCommandResponse))]
[JsonSerializable(typeof(CreateDiagnosticCommandResponse))]
[JsonSerializable(typeof(ServiceDiagnosticResponse[]))]
[JsonSerializable(typeof(InstallCommandRequest))]
[JsonSerializable(typeof(InstallCommandResponse))]
[JsonSerializable(typeof(CreateServiceRequest))]
[JsonSerializable(typeof(UpdateServiceRequest))]
[JsonSerializable(typeof(SetServiceEnabledRequest))]
[JsonSerializable(typeof(SetBackendUpdatePolicyRequest))]
[JsonSerializable(typeof(RequestBackendUpdateResponse))]
[JsonSerializable(typeof(ServerUpdateRequestResponse))]
[JsonSerializable(typeof(ServerUpdateStatus))]
[JsonSerializable(typeof(ServiceMutationResponse))]
[JsonSerializable(typeof(AdminServiceResponse[]))]
[JsonSerializable(typeof(LoginRequest))]
[JsonSerializable(typeof(LoginResponse))]
[JsonSerializable(typeof(UserResponse))]
[JsonSerializable(typeof(UserResponse[]))]
[JsonSerializable(typeof(CreateUserRequest))]
[JsonSerializable(typeof(UpdateUserRequest))]
[JsonSerializable(typeof(CreateUserResponse))]
[JsonSerializable(typeof(RotateSubscriptionTokenResponse))]
[JsonSerializable(typeof(UserServiceAccessResponse[]))]
[JsonSerializable(typeof(UsageTotalResponse[]))]
[JsonSerializable(typeof(Guid[]))]
[JsonSerializable(typeof(ServicePublicEndpointRequest))]
[JsonSerializable(typeof(ServicePublicEndpointResponse))]
[JsonSerializable(typeof(CreateServiceTemplateRequest))]
[JsonSerializable(typeof(UpdateServiceTemplateRequest))]
[JsonSerializable(typeof(ServiceTemplateResponse))]
[JsonSerializable(typeof(ServiceTemplateResponse[]))]
[JsonSerializable(typeof(CreateServiceFromTemplateRequest))]
[JsonSerializable(typeof(BatchServiceEnabledRequest))]
[JsonSerializable(typeof(BatchServiceEnabledResponse))]
[JsonSerializable(typeof(HealthSummaryResponse))]
[JsonSerializable(typeof(SetAgentUpdatePolicyRequest))]
[JsonSerializable(typeof(RequestAgentUpdateResponse))]
[JsonSerializable(typeof(BatchAgentUpdateRequest))]
[JsonSerializable(typeof(BatchAgentUpdateResponse))]
internal sealed partial class ServerJsonSerializerContext : JsonSerializerContext;
