namespace HyPanel.Server.Endpoints;

using System.Text.Json.Serialization;

[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
[JsonSerializable(typeof(CreateNodeRequest))]
[JsonSerializable(typeof(CreateNodeResponse))]
[JsonSerializable(typeof(CreateEnrollmentTokenResponse))]
[JsonSerializable(typeof(AdminNodeObservationResponse[]))]
[JsonSerializable(typeof(CreateHealthCheckCommandResponse))]
[JsonSerializable(typeof(InstallCommandRequest))]
[JsonSerializable(typeof(InstallCommandResponse))]
[JsonSerializable(typeof(CreateServiceRequest))]
[JsonSerializable(typeof(UpdateServiceRequest))]
[JsonSerializable(typeof(SetServiceEnabledRequest))]
[JsonSerializable(typeof(ServiceMutationResponse))]
[JsonSerializable(typeof(AdminServiceResponse[]))]
[JsonSerializable(typeof(LoginRequest))]
[JsonSerializable(typeof(LoginResponse))]
[JsonSerializable(typeof(UserResponse))]
[JsonSerializable(typeof(UserResponse[]))]
[JsonSerializable(typeof(CreateUserRequest))]
[JsonSerializable(typeof(UpdateUserRequest))]
[JsonSerializable(typeof(CreateUserResponse))]
[JsonSerializable(typeof(RotateSubscriptionTokenResponse))]
[JsonSerializable(typeof(UsageTotalResponse[]))]
[JsonSerializable(typeof(Guid[]))]
[JsonSerializable(typeof(ServicePublicEndpointRequest))]
[JsonSerializable(typeof(ServicePublicEndpointResponse))]
[JsonSerializable(typeof(CreateServiceTemplateRequest))]
[JsonSerializable(typeof(UpdateServiceTemplateRequest))]
[JsonSerializable(typeof(ServiceTemplateResponse))]
[JsonSerializable(typeof(ServiceTemplateResponse[]))]
[JsonSerializable(typeof(CreateServiceFromTemplateRequest))]
[JsonSerializable(typeof(BatchServiceEnabledRequest))]
[JsonSerializable(typeof(BatchServiceEnabledResponse))]
[JsonSerializable(typeof(HealthSummaryResponse))]
internal sealed partial class ServerJsonSerializerContext : JsonSerializerContext;
